name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      push:
        description: 'push image or not'
        type: boolean
        default: false
      containerfile:
        description: 'Dockerfile path'
        type: string
        default: 'Dockerfile'
      image_name:
        description: 'image name'
        type: string
        required: true
      tag:
        description: 'image tag'
        type: string
        default: ''
      no-cache:
        description: 'docker/build-push-action@v5 no-cache option'
        type: boolean
        default: false
      runson:
        description: 'runner'
        type: string
        default: 'ubuntu-latest'
      build-args:
        description: 'docker/build-push-action@v5 build arguments'
        type: string
        default: ''
      image_prefix:
        description: 'image prefix'
        type: string
        default: 'flagbase'
    secrets:
      CONTAINER_REGISTRY:
        description: 'Docker Registry Token'
        required: true
      REGISTRY_USERNAME:
        description: 'Docker Registry username'
        required: true
      RUNNER_SSH_KEY:
        description: 'SSH Private key for CI Runners'
        required: true

env:
  REGISTRY: harbor.baai.ac.cn

jobs:
  build-image:
    runs-on: ${{ inputs.runson }}
    steps:
      - name: Debug all inputs
        run: |
          echo "push: ${{ inputs.push }}"
          echo "containerfile: ${{ inputs.containerfile }}"
          echo "image_name: ${{ inputs.image_name }}"
          echo "tag: ${{ inputs.tag }}"
          echo "runson: ${{ inputs.runson }}"
          echo "build-args: '${{ inputs.build-args }}'"

      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.RUNNER_SSH_KEY }}
          submodules: true

      - name: Log in to the Container registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v3.7.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push }}
          file: container/${{ inputs.containerfile }}
          tags: |
            ${{ env.REGISTRY }}/${{ inputs.image_prefix }}/${{ inputs.image_name }}:${{ inputs.tag }}
          labels: ${{ inputs.tag }}
          no-cache: ${{ inputs.no-cache }}
          build-args: ${{ inputs.build-args }}
