name: Push and Scheduled Docker Image Build Orchestrator 

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      push_images:
        description: 'push image or not'
        type: boolean
        default: true

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: checkout_code
        name: Checkout Code
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.RUNNER_SSH_KEY }}

      - id: set-matrix
        run: |
          # Generate matrix for vendors
          ./generate_matrix.sh > matrix.json
          
          # Dump matrix to job output
          MATRIX_CONTENT=$(cat matrix.json | jq -c .)
          echo "matrix=$MATRIX_CONTENT" >> $GITHUB_OUTPUT
        shell: bash

  build-matrix:
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    name: ${{ matrix.job_name }}
    uses: ./.github/workflows/imagebuild.yml
    with:
      push: true
      containerfile: ${{ matrix.containerfile }}
      image_name: ${{ matrix.image_name }}
      tag: ${{ matrix.tag }}
      runson: ${{ matrix.runson }}
      build-args: ${{ matrix.build-args }}
      image_prefix: 'flagbase'
      no-cache: true
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      RUNNER_SSH_KEY: ${{ secrets.RUNNER_SSH_KEY }}
