name: Scheduled Docker Image Build Orchestrator 

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      push_images:
        description: 'push image or not'
        type: boolean
        default: false

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: checkout_code
        name: Checkout Code
        uses: actions/checkout@v6
      - id: set-matrix
        run: |
          # 使用动态生成的矩阵从 vendor_json 目录
          ./generate_matrix.sh true true > matrix.json
          
          # 读取 JSON 文件并输出
          MATRIX_CONTENT=$(cat matrix.json | jq -c .)
          echo "matrix=$MATRIX_CONTENT" >> $GITHUB_OUTPUT
        shell: bash

  build-matrix:
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    name: ${{ matrix.job_name }}
    uses: ./.github/workflows/imagebuild.yml
    with:
      push: true
      containerfile: ${{ matrix.containerfile }}
      image_name: ${{ matrix.image_name }}
      tag: ${{ matrix.tag }}
      runson: ${{ matrix.runson }}
      build-args: ${{ matrix.build-args }}
      image_prefix: 'flagbase'
      no-cache: true
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
