name: Scheduled Docker Image Build Orchestrator 

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      push_images:
        description: 'push image or not'
        type: boolean
        default: false

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          # 使用 heredoc 创建有效的 JSON
          cat > matrix.json << 'EOF'
          {
            "include": [
              {
                "job_name": "build-base-nvidia-image",
                "push": false,
                "containerfile": "containerfile.nvidia",
                "tag": "flagbase-nvidia",
                "label": "latest",
                "runson": "h20",
                "build-args": ""
              },
              {
                "job_name": "build-base-nvidia-image-py312torch2.8",
                "push": false,
                "containerfile": "containerfile.nvidia",
                "tag": "flagbase-nvidia",
                "label": "py312torch2.8",
                "runson": "h20",
                "build-args": "PYTHON_VERSION=3.12\nTORCH_VERSION=2.8"
              },
              {
                "job_name": "build-base-metax-image",
                "push": true,
                "containerfile": "containerfile.metax",
                "tag": "flagbase-metax",
                "label": "latest",
                "runson": "h20",
                "build-args": "ubuntu_version=22.04"
              },
              {
                "job_name": "build-base-amd-image",
                "push": true,
                "containerfile": "containerfile.amd",
                "tag": "flagbase-amd",
                "label": "latest",
                "runson": "h20",
                "build-args": ""
              }
            ]
          }
          EOF
          
          # 读取 JSON 文件并输出
          MATRIX_CONTENT=$(cat matrix.json | jq -c .)
          echo "matrix=$MATRIX_CONTENT" >> $GITHUB_OUTPUT
        shell: bash

  build-matrix:
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    name: ${{ matrix.job_name }}
    uses: ./.github/workflows/imagebuild.yml
    with:
      push: ${{ matrix.push }}
      containerfile: ${{ matrix.containerfile }}
      tag: ${{ matrix.tag }}
      label: ${{ matrix.label }}
      runson: ${{ matrix.runson }}
      build-args: ${{ matrix.build-args }}
      image_prefix: 'flagbase'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
