name: Docker Image Build Orchestrator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: |
          echo 'matrix={ "include": [ 
            { 
              "job_name": "build-base-nvidia-image", 
              "push": "false",
              "containerfile": "containerfile.nvidia",
              "tag": "flagbase-nvidia",
              "label": "latest",
              "runson": "h20",
              "build-args": ""
            }, 
            {
              "job_name": "build-base-nvidia-image-py312torch2.8",
              "push": "false",
              "containerfile": "containerfile.nvidia",
              "tag": "flagbase-nvidia",
              "label": "py312torch2.8",
              "runson": "h20",
              "build-args": "PYTHON_VERSION=3.12\nTORCH_VERSION=2.8"
            },
            {
              "job_name": "build-base-metax-image",
              "push": true,
              "containerfile": "containerfile.metax",
              "tag": "flagbase-metax",
              "label": "latest",
              "runson": "h20",
              "build_args": ""
            },
            {
              "job_name": "build-base-amd-image",
              "push": true,
              "containerfile": "containerfile.amd",
              "tag": "flagbase-amd",
              "label": "latest",
              "runson": "h20",
              "build_args": ""
            },
          ] }' >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          # GHA default instance will meet no space left on device issue
          - job_name: build-base-nvidia-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile.nvidia'
            image_name: 'flagbase-nvidia'
            tag: 'latest'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              GPU_TYPE=nvidia
          # GHA default instance will meet no space left on device issue
          - job_name: build-base-nvidia-image-py312torch2.8
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile.nvidia'
            image_name: 'flagbase-nvidia'
            tag: 'py312torch2.8'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              PYTHON_VERSION=3.12
              TORCH_VERSION=2.8
              GPU_TYPE=nvidia
          # GHA default instance will meet no space left on device issue
          - job_name: build-base-metax-image
            push: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            containerfile: 'containerfile.metax'
            image_name: 'flagbase-metax'
            tag: 'latest'
            runson: 'h20'
            no-cache: ${{ github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' && inputs.push_images }}
            build-args: |
              ubuntu_version=22.04
              GPU_TYPE=metax
    
      matrix: ${{ fromJSON(needs.set-matrix.outputs.matrix) }}
    name: ${{ matrix.job_name }}
    uses: ./.github/workflows/imagebuild.yml
    with:
      push: ${{ matrix.push }}
      containerfile: ${{ matrix.containerfile }}
      image_name: ${{ matrix.image_name }}
      tag: ${{ matrix.tag }}
      runson: ${{ matrix.runson }}
      build-args: ${{ matrix.build-args }}
      image_prefix: 'flagbase'
      no-cache: ${{ matrix.no-cache }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
